version: '3.6'
services:
  postgres:
    container_name: utfparking
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: utfparking
      POSTGRES_DB: utfparking
